"base_path": "."

"preserve_hierarchy": true

files:
  - source: /assets/minecraft/lang/en_us.json
    translation: /assets/minecraft/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore: 
        # ONLY CHANGE THIS IF THERE ARE NEW LANGS SO THAT THEY CAN MATCH MINECRAFT
        # https://support.crowdin.com/developer/language-codes/
        de: de_de
        en-CA: en_ca
        en-GB: en_gb
        en-PT: en_pt
        en-UD: en_ud
        es-ES: es_es
        es-AR: es_ar
        fr: fr_fr
        hu: hu_hu
        ja: ja_jp
        lol: lol_us
        pt-PT: pt_pt
        pt-BR: pt_br
        ro: ro_ro
        ru: ru_ru
        uk: uk_ua
        vi: vi_vn
        # do not take this out of order or else KTrain will eat you
    skip_untranslated_strings: false
    export_only_approved: false
