"base_path": "."

"preserve_hierarchy": true

files:
  - source: /assets/minecraft/lang/en_us.json
    translation: /assets/minecraft/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore: # ABSOLULTELY DO NOT CHANGE THIS
        de: de_de
        en-UD: en_ud
        es-ES: es_es
        fr: fr_fr
        lol: lol_us
        pt-BR: pt_br
        ru: ru_ru
    skip_untranslated_strings: false
    export_only_approved: false
