"base_path": "."

"preserve_hierarchy": true

files:
  - source: /assets/minecraft/lang/en_us.json
    translation: /assets/minecraft/lang/%locale_with_underscore%.json
    language_mapping:
      locale_with_underscore: # ABSOLULTELY DO NOT CHANGE THIS
        de_de: de
        en_ud: en-UD
        es_es: es-ES
        fr_fr: fr
        lol_us: lol-US
        pt_br: pt-BR
        ru_ru: ru
    upload_language: en
    skip_untranslated_strings: false
    export_only_approved: false
