skins.1=1
name.1=Gay
skins.2=2
name.2=MLM
skins.3=3
name.3=Lesbian
skins.4=4
name.4=Bisexual
skins.5=5
name.5=Trans
skins.6=6
name.6=Pansexual
skins.7=7 	
name.7=Queer
skins.8=8
name.8=Non-Binary
skins.9=9
name.9=Intersex
skins.10=10
name.10=Agender
skins.11=11
name.11=Bigender
skins.12=12
name.12=Aroace
skins.13=13
name.13=Asexual
skins.14=14
name.14=Aromantic
skins.15=15
name.15=Aplatonic
skins.16=16
name.16=Gender Fluid

skins.17=1-15